<?php
return array(
    'seo_url' => array(
        '/catalogs' => array(
            'ct_shop_table_rubrics' => array(
                'url' => '/catalogs', 
                'params' => array(
                    'id' => 'rubric', ), ), 
            'ct_shop_goods' => array(
                'url' => '/goods', 
                'params' => array(
                    'id' => 'id', ), ), ), 
        '/articles' => array(
            'ct_shop_news' => array(
                'url' => '/article', 
                'params' => array(
                    'id' => 'id', ), ), ), ), 
    'basic' => array(
        1558242197 => array(
            'title' => 'Телефоны с верху', 
            'db_object' => 'DB_Shop_AddressContact',
            'function' => 'find',
            'one' => 'View_Shop_AddressContact\-telefony-s-verkhu', 
            'params' => array(
                'sort_by' => array(
                    'is_public' => '1',
                    'value' => array('id' => 'asc'),
                ),
                'limit' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_address_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'contact_type_id' => array(
                    'is_public' => '1', 
                    'value' => '13, 14', 
                    'field' => '', ), 
                'city_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'land_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_AddressContacts\-telefony-s-verkhu', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1558242198 => array(
            'title' => 'Кнопка звонка', 
            'db_object' => 'DB_Shop_AddressContact',
            'function' => 'find',
            'one' => 'View_Shop_AddressContact\-knopka-zvonka', 
            'params' => array(
                'sort_by' => array(
                    'is_public' => '1',
                    'value' => array('id' => 'asc'),
                ),
                'limit' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_address_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'contact_type_id' => array(
                    'is_public' => '1', 
                    'value' => '13, 14', 
                    'field' => '', ), 
                'city_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'land_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_AddressContacts\-knopka-zvonka', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1558242199 => array(
            'title' => 'Социальные сети', 
            'db_object' => 'DB_Shop_New',
            'function' => 'find',
            'one' => 'View_Shop_New\-sotcialnye-seti', 
            'params' => array(
                'param_index' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '1', 
                    'value' => '3981', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_News\-sotcialnye-seti', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), ), 
    'urls' => array(
        '' => array(
            'main' => '/main/index', 
            'data' => array(
                1558243100 => array(
                    'title' => 'Слайдер на главной', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-slaider-na-glavnoi', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '10', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3982', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-slaider-na-glavnoi', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1558243312 => array(
                    'title' => 'Направления', 
                    'db_object' => 'DB_Shop_Good',
                    'function' => 'find',
                    'one' => 'View_Shop_Good\-napravleniya', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '4', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3983', 
                            'field' => '', ), 
                        'root_id' => array(
                            'is_public' => '1',
                            'value' => '0',
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Goods\-napravleniya', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1558247281 => array(
                    'title' => 'Карта', 
                    'db_object' => 'DB_Shop_Address',
                    'function' => 'getMainShopAddress', 
                    'one' => 'View_Shop_Address\-karta', 
                    'params' => array(), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1558247520 => array(
                    'title' => 'Филиалы', 
                    'db_object' => 'DB_Shop_Address',
                    'function' => 'findShopAddressWithContacts', 
                    'one' => 'View_Shop_Address\-filialy', 
                    'params' => array(
                        'sort_by' => array(
                            'is_public' => '1',
                            'value' => array('id' => 'asc'),
                        ),
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'city_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'land_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Addresss\-filialy', 
                    'group' => array(
                        'one' => 'View_Shop_Address\group\-filialy', 
                        'list' => 'View_Shop_Addresss\group\-filialy', 
                        'params' => array(
                            'sort_by' => array(
                                'is_public' => '1',
                                'value' => array('id' => 'asc'),
                            ),
                            'limit' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'limit_page' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'is_not_read_request' => array(
                                'is_public' => '1', 
                                'value' => '1', 
                                'field' => '', ), 
                            'type' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'name' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'city_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'land_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'is_branch' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'shop_branch_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'text' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'options' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'is_public' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'shop_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'update_user_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'create_user_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), ), 
                        'read_request_type' => array(
                            'params' => array(
                                'is_read' => '1', 
                                'priority' => '1', ), 
                            'get' => array(
                                'is_read' => '0', 
                                'priority' => '', ), 
                            'post' => array(
                                'is_read' => '0', 
                                'priority' => '', ), ), ), 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Главная', ), 
        '/contacts' => array(
            'main' => '/main/contacts', 
            'data' => array(
                1558247281 => array(
                    'title' => 'Карта', 
                    'db_object' => 'DB_Shop_Address',
                    'function' => 'getMainShopAddress', 
                    'one' => 'View_Shop_Address\-karta', 
                    'params' => array(), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1558247520 => array(
                    'title' => 'Филиалы', 
                    'db_object' => 'DB_Shop_Address',
                    'function' => 'findShopAddressWithContacts', 
                    'one' => 'View_Shop_Address\-filialy', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'city_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'land_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Addresss\-filialy', 
                    'group' => array(
                        'one' => 'View_Shop_Address\group\-filialy', 
                        'list' => 'View_Shop_Addresss\group\-filialy', 
                        'params' => array(
                            'limit' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'limit_page' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'is_not_read_request' => array(
                                'is_public' => '1', 
                                'value' => '1', 
                                'field' => '', ), 
                            'type' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'name' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'city_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'land_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'is_branch' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'shop_branch_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'text' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'options' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'is_public' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'shop_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'update_user_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'create_user_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), ), 
                        'read_request_type' => array(
                            'params' => array(
                                'is_read' => '1', 
                                'priority' => '1', ), 
                            'get' => array(
                                'is_read' => '0', 
                                'priority' => '', ), 
                            'post' => array(
                                'is_read' => '0', 
                                'priority' => '', ), ), ), 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Контакты', ), 
        '/catalogs' => array(
            'main' => '/main/catalogs', 
            'data' => array(
                1558248503 => array(
                    'title' => 'Рубрика',
                    'db_object' => 'DB_Shop_Table_Rubric',
                    'function' => 'findOne',
                    'one' => 'View_Shop_Good\-catalogs-rubrika', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'rubric', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1558248504 => array(
                    'title' => 'Продукция', 
                    'db_object' => 'DB_Shop_Good',
                    'function' => 'find',
                    'one' => 'View_Shop_Good\-catalogs-produktciya', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '1', 
                            'value' => '8', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3983', 
                            'field' => '', ), 
                        'main_shop_table_rubric_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'rubric', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Goods\-catalogs-produktciya', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1558248662 => array(
                    'title' => 'Хлебные крошки', 
                    'db_object' => 'DB_Shop_Table_Rubric',
                    'function' => 'findBreadCrumbs',
                    'one' => 'View_Shop_Table_Rubric\-catalogs-khlebnye-kroshki', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '999', 
                            'field' => '_root_id_', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Table_Rubrics\-catalogs-khlebnye-kroshki', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Каталог', ), 
        '/goods' => array(
            'main' => '/main/goods', 
            'data' => array(
                1558249462 => array(
                    'title' => 'Продукт', 
                    'db_object' => 'DB_Shop_Good',
                    'function' => 'findOne',
                    'one' => 'View_Shop_Good\-goods-produkt', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1558248662 => array(
                    'title' => 'Хлебные крошки', 
                    'db_object' => 'DB_Shop_Table_Rubric',
                    'function' => 'findBreadCrumbs',
                    'one' => 'View_Shop_Table_Rubric\-catalogs-khlebnye-kroshki', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '999', 
                            'field' => '_root_id_', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Table_Rubrics\-catalogs-khlebnye-kroshki', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Товар', ), 
        '/about' => array(
            'main' => '/main/about', 
            'data' => array(
                1558248247 => array(
                    'title' => 'О компании', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-about-o-kompanii', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3984', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-about-o-kompanii', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'О компании', ), 
        '/cart' => array(
            'main' => '/main/cart', 
            'data' => array(
                1559050766 => array(
                    'title' => 'Товары', 
                    'db_object' => 'DB_Shop_Cart',
                    'function' => 'getCartShopGoods', 
                    'one' => 'View_Shop_Cart\-cart-tovary', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Carts\-cart-tovary', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Корзина', ), ), );