<?php
return array(
    'seo_url' => array(
        '/catalogs' => array(
            'ct_shop_table_rubrics' => array(
                'url' => '/catalogs', 
                'params' => array(
                    'id' => 'rubric_id', ), ), 
            'ct_shop_goods' => array(
                'url' => '/goods', 
                'params' => array(
                    'id' => 'id', ), ), ), ), 
    'basic' => array(
        1540734657 => array(
            'title' => 'Социальные сети', 
            'db_object' => 'DB_Shop_New', 
            'function' => 'find',
            'one' => 'View_Shop_New\basic\sotcialnye-seti', 
            'params' => array(
                'sort_by' => array(
                    'is_public' => '1',
                    'value' => array(
                        'order' => 'asc',
                        'id' => 'desc', ),
                    'field' => '', ),
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '1', 
                    'value' => '3859', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_News\basic\sotcialnye-seti', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1540735363 => array(
            'title' => 'Языки',
            'class' => 'View_Shop',
            'db_object' => 'DB_Language', 
            'function' => 'getShopLanguages', 
            'one' => 'View_Language\basic\yazyki', 
            'params' => array(), 
            'list' => 'View_Languages\basic\yazyki', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1541311719 => array(
            'title' => 'Пользователь', 
            'db_object' => 'DB_User', 
            'function' => 'getUserCurrent', 
            'one' => 'View_User\basic\polzovatel', 
            'params' => array(
                'is_error_404' => array(
                    'is_public' => '1', 
                    'value' => '0', 
                    'field' => '', ), ), 
            'list' => '', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ),

        999 => array(
            'title' => 'Кол-во посылок по статусам',
            'db_object' => 'DB_Ads_Shop_Parcel',
            'function' => 'findShopParcelsAuthUser',
            'one' => 'View_Ads_Shop_Parcel\user-menu',
            'params' => array(
                'limit' => array(
                    'is_public' => '0',
                    'value' => '',
                    'field' => '', ),
                'limit_page' => array(
                    'is_public' => '0',
                    'value' => '',
                    'field' => '', ),
                'is_not_read_request' => array(
                    'is_public' => '1',
                    'value' => '1',
                    'field' => '', ),
                'count_parcel_status_id' => array(
                    'is_public' => '1',
                    'value' => TRUE,
                    'field' => '', ), ),
            'list' => 'View_Ads_Shop_Parcels\user-menu',
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1',
                    'priority' => '', ),
                'get' => array(
                    'is_read' => '1',
                    'priority' => '', ),
                'post' => array(
                    'is_read' => '1',
                    'priority' => '', ), ), ),),
    'urls' => array(
        '' => array(
            'main' => '/main/index', 
            'data' => array(
                1540736336 => array(
                    'title' => 'Первая картинка на главной', 
                    'db_object' => 'DB_Shop_New', 
                    'function' => 'find',
                    'one' => 'View_Shop_New\-pervaya-kartinka-na-glavnoi', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3860', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-pervaya-kartinka-na-glavnoi', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1540736473 => array(
                    'title' => 'Как это работает?', 
                    'db_object' => 'DB_Shop_New', 
                    'function' => 'find',
                    'one' => 'View_Shop_New\-kak-eto-rabotaet', 
                    'params' => array(
                'sort_by' => array(
                    'is_public' => '1',
                    'value' => array(
                        'order' => 'asc',
                        'id' => 'desc', ),
                    'field' => '', ),
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '3', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3861', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-kak-eto-rabotaet', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1540736474 => array(
                    'title' => 'Почему ADS?', 
                    'db_object' => 'DB_Shop_New', 
                    'function' => 'find',
                    'one' => 'View_Shop_New\-pochemu-ads', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '4', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3862', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-pochemu-ads', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1540736475 => array(
                    'title' => 'Наш логистический партнер', 
                    'db_object' => 'DB_Shop_New', 
                    'function' => 'find',
                    'one' => 'View_Shop_New\-nash-logisticheskii-partner', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3863', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-nash-logisticheskii-partner', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Главная', ), 
        '/how-it-works' => array(
            'main' => '/main/how-it-works', 
            'data' => array(), 
            'title' => 'Как это работает?', ), 
        '/services' => array(
            'main' => '/main/services', 
            'data' => array(), 
            'title' => 'Услуги', ), 
        '/delivery' => array(
            'main' => '/main/delivery', 
            'data' => array(), 
            'title' => 'Доставка', ), 
        '/faq' => array(
            'main' => '/main/faq', 
            'data' => array(), 
            'title' => 'Вопросы/ответы', ), 
        '/contacts' => array(
            'main' => '/main/contacts', 
            'data' => array(), 
            'title' => 'Контакты', ), 
        '/account' => array(
            'main' => '/main/account', 
            'data' => array(
                1541051821 => array(
                    'title' => 'Клиент', 
                    'db_object' => 'DB_Ads_Shop_Client', 
                    'function' => 'getShopClientAuthUser', 
                    'one' => 'View_Ads_Shop_Client\account-klient', 
                    'params' => array(), 
                    'list' => '', 
                    'elements' => array(
                        'user_id' => array(
                            0 => 'email', ), ), 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '', ), ), ), ), 
            'redirect' => 'checkAccountUser', 
            'title' => 'Мой аккаунт', ), 
        '/account/expect' => array(
            'main' => '/main/account-expect', 
            'redirect' => 'checkAccountUser', 
            'data' => array(
                1541318159 => array(
                    'title' => 'Ожидаемые', 
                    'db_object' => 'DB_Ads_Shop_Parcel', 
                    'function' => 'findShopParcelsAuthUser', 
                    'one' => 'View_Ads_Shop_Parcel\-account-expect-ozhidaemye', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'parcel_status_id' => array(
                            'is_public' => '1', 
                            'value' => 1, 
                            'field' => '', ), ), 
                    'list' => 'View_Ads_Shop_Parcels\-account-expect-ozhidaemye', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Ожидаемые', ), 
        '/account/stock' => array(
            'main' => '/main/account-stock', 
            'redirect' => 'checkAccountUser', 
            'data' => array(
                1541056059 => array(
                    'title' => 'Адреса',
                    'db_object' => 'DB_Ads_Shop_Client',
                    'function' => 'getShopClientAuthUser',
                    'one' => 'View_Ads_Shop_Client\addresses',
                    'params' => array(),
                    'list' => '',
                    'elements' => array(
                        'user_id' => array(
                            0 => 'email', ), ),
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1',
                            'priority' => '', ),
                        'get' => array(
                            'is_read' => '1',
                            'priority' => '', ),
                        'post' => array(
                            'is_read' => '1',
                            'priority' => '', ), ), ),
                1541319530 => array(
                    'title' => 'На складе', 
                    'db_object' => 'DB_Ads_Shop_Parcel', 
                    'function' => 'findShopParcelsAuthUser', 
                    'one' => 'View_Ads_Shop_Parcel\-account-stock-na-sklade', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'parcel_status_id' => array(
                            'is_public' => '1', 
                            'value' => Model_Ads_ParcelStatus::PARCEL_STATUS_IN_STOCK,
                            'field' => '', ), ), 
                    'list' => 'View_Ads_Shop_Parcels\-account-stock-na-sklade', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Адреса', ),
        '/account/sent' => array(
            'main' => '/main/account-sent', 
            'redirect' => 'checkAccountUser', 
            'data' => array(
                1541320130 => array(
                    'title' => 'Отправленные', 
                    'db_object' => 'DB_Ads_Shop_Parcel', 
                    'function' => 'findShopParcelsAuthUser', 
                    'one' => 'View_Ads_Shop_Parcel\-account-sent-otpravlennye', 
                    'elements' => array(
                        'shop_client_id' => array(
                            0 => 'name', ), ), 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'parcel_status_id' => array(
                            'is_public' => '1', 
                            'value' => 3, 
                            'field' => '', ), ), 
                    'list' => 'View_Ads_Shop_Parcels\-account-sent-otpravlennye', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Отправлено', ),
        '/account/delivered' => array(
            'main' => '/main/account-delivered',
            'redirect' => 'checkAccountUser',
            'data' => array(
                1541320130 => array(
                    'title' => 'Доставлено',
                    'db_object' => 'DB_Ads_Shop_Parcel',
                    'function' => 'findShopParcelsAuthUser',
                    'one' => 'View_Ads_Shop_Parcel\-account-delivered',
                    'elements' => array(
                        'shop_client_id' => array(
                            0 => 'name', ), ),
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'limit_page' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_not_read_request' => array(
                            'is_public' => '1',
                            'value' => '1',
                            'field' => '', ),
                        'parcel_status_id' => array(
                            'is_public' => '1',
                            'value' => 5,
                            'field' => '', ), ),
                    'list' => 'View_Ads_Shop_Parcels\-account-delivered',
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1',
                            'priority' => '', ),
                        'get' => array(
                            'is_read' => '1',
                            'priority' => '', ),
                        'post' => array(
                            'is_read' => '1',
                            'priority' => '', ), ), ), ),
            'title' => 'Доставлено', ),
        '/account/profile/edit' => array(
            'main' => '/main/account-profile-edit', 
            'redirect' => 'checkAccountUser', 
            'data' => array(
                1541060396 => array(
                    'title' => 'Страны', 
                    'db_object' => 'DB_Land', 
                    'function' => 'findAll',
                    'one' => 'View_Land\-account-profile-edit-strany', 
                    'params' => array(), 
                    'list' => 'View_Lands\-account-profile-edit-strany', 
                    'read_request_type' => array(
                        'sort_by' => array(
                            'is_public' => '1',
                            'value' => array(
                                'name' => 'asc',
                                'id' => 'desc', ),
                            'field' => '', ),
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '', ), ), ), 
                1541056059 => array(
                    'title' => 'Данные пользователя', 
                    'db_object' => 'DB_Ads_Shop_Client', 
                    'function' => 'getShopClientAuthUser', 
                    'one' => 'View_Ads_Shop_Client\-account-profile-edit-dannye-polzovatelya', 
                    'params' => array(), 
                    'list' => '', 
                    'elements' => array(
                        'user_id' => array(
                            0 => 'email', ), ), 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Редактирование данных пользователя', ),
        '/cities' => array(
            'main' => '/main/cities',
            'data' => array(
                1541060397 => array(
                    'title' => 'Города',
                    'db_object' => 'DB_City',
                    'function' => 'find',
                    'one' => 'View_City\-account-profile-edit-goroda',
                    'params' => array(
                        'sort_by' => array(
                            'is_public' => '1',
                            'value' => array(
                                'name' => 'asc',
                                'id' => 'desc', ),
                            'field' => '', ),
                        'land_id' => array(
                            'is_public' => '1',
                            'value' => '',
                            'field' => 'land_id', ),
                        'region_id' => array(
                            'is_public' => '1',
                            'value' => '',
                            'field' => 'region_id', ), ),
                    'list' => 'View_Citys\-account-profile-edit-goroda',
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1',
                            'priority' => '', ),
                        'get' => array(
                            'is_read' => '1',
                            'priority' => '', ),
                        'post' => array(
                            'is_read' => '1',
                            'priority' => '', ), ), ), ),
            'title' => 'Города', ),
        '/regions' => array(
            'main' => '/main/regions',
            'data' => array(
                1541060397 => array(
                    'title' => 'Области',
                    'db_object' => 'DB_Region',
                    'function' => 'find',
                    'one' => 'View_Region\-account-profile-edit-region',
                    'params' => array(
                        'sort_by' => array(
                            'is_public' => '1',
                            'value' => array(
                                'name' => 'asc',
                                'id' => 'desc', ),
                            'field' => '', ),
                        'land_id' => array(
                            'is_public' => '1',
                            'value' => '',
                            'field' => 'land_id', ), ),
                    'list' => 'View_Regions\-account-profile-edit-region',
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1',
                            'priority' => '', ),
                        'get' => array(
                            'is_read' => '1',
                            'priority' => '', ),
                        'post' => array(
                            'is_read' => '1',
                            'priority' => '', ), ), ), ),
            'title' => 'Области', ),
        '/account/auth' => array(
            'main' => '/main/account-auth', 
            'data' => array(), 
            'title' => 'Авторизация', ), 
        '/account/await/add' => array(
            'main' => '/main/account-await-add', 
            'redirect' => 'checkAccountUser', 
            'data' => array(),
            'title' => 'Добавить посылку', ), 
        '/account/invoice' => array(
            'main' => '/main/account-invoice', 
            'redirect' => 'checkAccountUser', 
            'data' => array(
                1541329703 => array(
                    'title' => 'Счета', 
                    'db_object' => 'DB_Ads_Shop_Invoice', 
                    'function' => 'findAuthUser', 
                    'one' => 'View_Ads_Shop_Invoice\-account-invoice-scheta',
                    'elements' => array('shop_parcel_id' => array('tracker', 'amount', 'text')),
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Ads_Shop_Invoices\-account-invoice-scheta', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Счета', ), 
        '/account/reset' => array(
            'main' => '/main/account-reset', 
            'data' => array(), 
            'title' => 'Восстановление пароля', ), 
        '/account/reset/ok' => array(
            'main' => '/main/account-reset-ok', 
            'data' => array(), 
            'title' => 'Восстановление пароля успешно', ), ), );