<?php
return array(
    'seo_url' => array(
        '/articles' => array(
            'ct_shop_table_rubrics' => array(
                'url' => '/articles', 
                'params' => array(
                    'id' => 'rubric_id', ), ), 
            'ct_shop_news' => array(
                'url' => '/article', 
                'params' => array(
                    'id' => 'id', ), ), ), ), 
    'basic' => array(
        1535361689 => array(
            'title' => 'Социальные сети', 
            'db_object' => 'DB_Shop_New',
            'function' => 'find',
            'one' => 'View_Shop_New\basic\sotcialnye-seti', 
            'params' => array(
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '1', 
                    'value' => '3875', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_News\basic\sotcialnye-seti', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), ), 
    'urls' => array(
        '' => array(
            'main' => '/main/index', 
            'data' => array(
                1534069057 => array(
                    'title' => 'Отзывы', 
                    'db_object' => 'DB_Shop_Comment',
                    'function' => 'find',
                    'one' => 'View_Shop_Comment\-otzyvy', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '15', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3808', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Comments\-otzyvy', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1534069058 => array(
                    'title' => 'Преимущества', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-preimushchestva', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3809', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-preimushchestva', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1534069059 => array(
                    'title' => 'О компании', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-o-kompanii', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3810', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-o-kompanii', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1535359529 => array(
                    'title' => 'Сертификаты', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-sertifikaty', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3864', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-sertifikaty', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Главная', 
            'site_title' => array(
                35 => 'BigBuh - онлайн бухгалтерия нового поколения. Цена 4499 тг/месяц. Всё включено.', ), 
            'site_keywords' => array(
                35 => 'онлайн бухгалтерия, ФНО 910 200 300, облачная бухгалтерия, бухгалтер онлайн, сдать налоговый отчет, бухгалтерские услуги алматы онлайн, бухгалтер удален, онлайн бухгалтерия казахстан', ), 
            'site_description' => array(
                35 => 'Онлайн бухгалтерия - автоматизированный онлайн сервис для ТОО и ИП, которые могут самостоятельно выставлять счета, акты, накладные, отправлять налоговые отчеты в один клик, рассчитывать зарплату, автозаполнение ФНО 910, 200, 300.', ), ), 
        '/about' => array(
            'main' => '/main/about', 
            'data' => array(
                1534070367 => array(
                    'title' => 'О нас', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\about-o-nas', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3810', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\about-o-nas', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'О нас', 
            'site_title' => array(
                35 => 'Bigbuh – это онлайн сервис по оказанию бухгалтерских услуг для ИП и ТОО на основе упрощенной декларации и по общеустановленному налоговому режиму. Сервис по автоматическому заполнению всех видов налоговых отчетов на основании первичных бухгалтерских документов. Вам не нужно нанимать бухгалтера в штат, и не нужно следить за обновлениями в законодательных актах по бухгалтерскому и налоговому учету, за этим будет следить Bigbuh, так как наш сервис полностью заменит бухгалтера.', ), 
            'site_keywords' => array(
                35 => 'онлайн бухгалтерия, ФНО 910 200 300, облачная бухгалтерия, бухгалтер онлайн, сдать налоговый отчет, бухгалтерские услуги алматы онлайн, бухгалтер удален, онлайн бухгалтерия казахстан', ), 
            'site_description' => array(
                35 => 'Онлайн сервис по оказанию бухгалтерских услуг для ИП и ТОО на основе упрощенной декларации и по общеустановленному режиму.', ), ), 
        '/client/register' => array(
            'main' => '/main/client_register', 
            'data' => array(), 
            'title' => 'Регистрация', 
            'site_title' => array(
                35 => 'Регистрация на портале онлайн бухгалтерии - BigBuh.kz', ), 
            'site_keywords' => array(
                35 => 'бухгалтерия, онлайн бухгалтерия, отчеты, 910 форма, 200 форма, 300 форма, налоговые отчеты, сдать отчет, квартальный отчет, бизнес, тоо, ип, вести бухгалтерию, аутсорсинг бухгалтерских услуг, бухгалтерские услуги, 1С-бухгалтерия, облачная бухгалтерия, регистрация онлайн бухгалтерия', ), 
            'site_description' => array(
                35 => 'Онлайн сервис по оказанию бухгалтерских услуг для ИП и ТОО на основе упрощенной декларации и по общеустановленному режиму.', ), ),
        '/client/reset' => array(
            'main' => '/main/client_reset',
            'data' => array(),
            'title' => 'Восстановление пароля',
            'site_title' => array(
                35 => 'Восстановление пароля на портале онлайн бухгалтерии - BigBuh.kz', ),
            'site_keywords' => array(
                35 => 'бухгалтерия, онлайн бухгалтерия, отчеты, 910 форма, 200 форма, 300 форма, налоговые отчеты, сдать отчет, квартальный отчет, бизнес, тоо, ип, вести бухгалтерию, аутсорсинг бухгалтерских услуг, бухгалтерские услуги, 1С-бухгалтерия, облачная бухгалтерия, регистрация онлайн бухгалтерия', ),
            'site_description' => array(
                35 => 'Онлайн сервис по оказанию бухгалтерских услуг для ИП и ТОО на основе упрощенной декларации и по общеустановленному режиму.', ), ),
        '/client/reset/finish' => array(
            'main' => '/main/client_reset_finish',
            'data' => array(),
            'title' => 'Восстановление пароля успешно',
            'site_title' => array(
                35 => 'Восстановление пароля на портале онлайн бухгалтерии - BigBuh.kz', ),
            'site_keywords' => array(
                35 => 'бухгалтерия, онлайн бухгалтерия, отчеты, 910 форма, 200 форма, 300 форма, налоговые отчеты, сдать отчет, квартальный отчет, бизнес, тоо, ип, вести бухгалтерию, аутсорсинг бухгалтерских услуг, бухгалтерские услуги, 1С-бухгалтерия, облачная бухгалтерия, регистрация онлайн бухгалтерия', ),
            'site_description' => array(
                35 => 'Онлайн сервис по оказанию бухгалтерских услуг для ИП и ТОО на основе упрощенной декларации и по общеустановленному режиму.', ), ),
        '/offers' => array(
            'main' => '/main/offers', 
            'data' => array(
                1535363808 => array(
                    'title' => 'Договор оферты', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\offers-dogovor-oferty', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3881', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\offers-dogovor-oferty', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Договор оферты', 
            'site_title' => array(
                35 => 'Публичная оферта оказания электронных услуг с интернет порталом Bigbuh', ), 
            'site_keywords' => array(
                35 => 'бухгалтерия, онлайн бухгалтерия, отчеты, 910 форма, 200 форма, 300 форма, налоговые отчеты, сдать отчет, квартальный отчет, бизнес, тоо, ип, вести бухгалтерию, аутсорсинг бухгалтерских услуг, бухгалтерские услуги, 1С-бухгалтерия, облачная бухгалтерия, регистрация онлайн бухгалтерия', ), 
            'site_description' => array(
                35 => 'Услуги - облачный сервис ведения бухгалтерского учета через интернет, т.е. электронные услуги (в том числе информационные, интерактивные, транзакционные), предоставляемые на территории Республики Казахстан совершеннолетним дееспособным физическим и юридическим лицам, с применением Информационных технологий', ), ), 
        '/what-offer' => array(
            'main' => '/main/what-offer', 
            'data' => array(
                1534069057 => array(
                    'title' => 'Отзывы', 
                    'db_object' => 'DB_Shop_Comment',
                    'function' => 'find',
                    'one' => 'View_Shop_Comment\-otzyvy', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '15', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3808', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Comments\-otzyvy', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Что мы предлагаем', 
            'site_title' => array(
                35 => 'Что мы предлагаем? BigBuh - онлайн бухгалтерия нового поколения', ), 
            'site_keywords' => array(
                35 => 'бухгалтерия, онлайн бухгалтерия, отчеты, 910 форма, 200 форма, 300 форма, налоговые отчеты, сдать отчет, квартальный отчет, бизнес, тоо, ип, вести бухгалтерию, аутсорсинг бухгалтерских услуг, бухгалтерские услуги, 1С-бухгалтерия, облачная бухгалтерия, регистрация онлайн бухгалтерия', ), 
            'site_description' => array(
                35 => 'Услуги - облачный сервис ведения бухгалтерского учета через интернет, т.е. электронные услуги (в том числе информационные, интерактивные, транзакционные), предоставляемые на территории Республики Казахстан совершеннолетним дееспособным физическим и юридическим лицам, с применением Информационных технологий', ), ), 
        '/comments' => array(
            'main' => '/main/comments', 
            'data' => array(
                1534069057 => array(
                    'title' => 'Отзывы', 
                    'db_object' => 'DB_Shop_Comment',
                    'function' => 'find',
                    'one' => 'View_Shop_Comment\-otzyvy', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '15', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3808', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Comments\-otzyvy', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Комментарии', 
            'site_title' => array(
                35 => 'Комментарии. BigBuh - онлайн бухгалтерия нового поколения', ), 
            'site_keywords' => array(
                35 => 'бухгалтерия, онлайн бухгалтерия, отчеты, 910 форма, 200 форма, 300 форма, налоговые отчеты, сдать отчет, квартальный отчет, бизнес, тоо, ип, вести бухгалтерию, аутсорсинг бухгалтерских услуг, бухгалтерские услуги, 1С-бухгалтерия, облачная бухгалтерия, регистрация онлайн бухгалтерия', ), 
            'site_description' => array(
                35 => 'Услуги - облачный сервис ведения бухгалтерского учета через интернет, т.е. электронные услуги (в том числе информационные, интерактивные, транзакционные), предоставляемые на территории Республики Казахстан совершеннолетним дееспособным физическим и юридическим лицам, с применением Информационных технологий', ), ), 
        '/articles' => array(
            'main' => '/main/articles', 
            'data' => array(
                1539269635 => array(
                    'title' => 'Статьи', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\articles-stati', 
                    'elements' => array(
                        'shop_table_rubric_id' => array(
                            0 => 'name', 
                            1 => 'name_url', ), ), 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '1', 
                            'value' => '9', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4306', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'rubric_id', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\articles-stati', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1539270944 => array(
                    'title' => 'Рубрика',
                    'db_object' => 'DB_Shop_Table_Rubric',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New\articles-rubrika', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'rubric_id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Рубрики новостей', 
            'site_title' => array(
                35 => 'Статьи. BigBuh - онлайн бухгалтерия нового поколения', ), 
            'site_keywords' => array(
                35 => 'бухгалтерия, онлайн бухгалтерия, отчеты, 910 форма, 200 форма, 300 форма, налоговые отчеты, сдать отчет, квартальный отчет, бизнес, тоо, ип, вести бухгалтерию, аутсорсинг бухгалтерских услуг, бухгалтерские услуги, 1С-бухгалтерия, облачная бухгалтерия, регистрация онлайн бухгалтерия', ), 
            'site_description' => array(
                35 => 'Услуги - облачный сервис ведения бухгалтерского учета через интернет, т.е. электронные услуги (в том числе информационные, интерактивные, транзакционные), предоставляемые на территории Республики Казахстан совершеннолетним дееспособным физическим и юридическим лицам, с применением Информационных технологий', ), ), 
        '/article' => array(
            'main' => '/main/article', 
            'data' => array(
                1539272182 => array(
                    'title' => 'Статья', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New\article-statya', 
                    'elements' => array(
                        'shop_table_rubric_id' => array(
                            0 => 'name', 
                            1 => 'name_url', ), ), 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Статьи', 
            'site_title' => array(
                35 => 'Статьи. BigBuh - онлайн бухгалтерия нового поколения', ), 
            'site_keywords' => array(
                35 => 'бухгалтерия, онлайн бухгалтерия, отчеты, 910 форма, 200 форма, 300 форма, налоговые отчеты, сдать отчет, квартальный отчет, бизнес, тоо, ип, вести бухгалтерию, аутсорсинг бухгалтерских услуг, бухгалтерские услуги, 1С-бухгалтерия, облачная бухгалтерия, регистрация онлайн бухгалтерия', ), 
            'site_description' => array(
                35 => 'Услуги - облачный сервис ведения бухгалтерского учета через интернет, т.е. электронные услуги (в том числе информационные, интерактивные, транзакционные), предоставляемые на территории Республики Казахстан совершеннолетним дееспособным физическим и юридическим лицам, с применением Информационных технологий', ), ), 
        '/partners' => array(
            'main' => '/main/partners', 
            'data' => array(
                1540628062 => array(
                    'title' => 'Партнерам', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\partners-partneram', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4406', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\partners-partneram', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Партнерам', 
            'site_title' => array(
                35 => 'Партнерам. BigBuh - онлайн бухгалтерия нового поколения', ), 
            'site_keywords' => array(
                35 => 'бухгалтерия, онлайн бухгалтерия, отчеты, 910 форма, 200 форма, 300 форма, налоговые отчеты, сдать отчет, квартальный отчет, бизнес, тоо, ип, вести бухгалтерию, аутсорсинг бухгалтерских услуг, бухгалтерские услуги, 1С-бухгалтерия, облачная бухгалтерия, регистрация онлайн бухгалтерия', ), 
            'site_description' => array(
                35 => 'Услуги - облачный сервис ведения бухгалтерского учета через интернет, т.е. электронные услуги (в том числе информационные, интерактивные, транзакционные), предоставляемые на территории Республики Казахстан совершеннолетним дееспособным физическим и юридическим лицам, с применением Информационных технологий', ), ), 
        '/packages' => array(
            'main' => '/main/packages', 
            'data' => array(
                1540636204 => array(
                    'title' => 'Пакеты', 
                    'db_object' => 'DB_Shop_Good',
                    'function' => 'find',
                    'one' => 'View_Shop_Good\packages-pakety', 
                    'params' => array(
                        'sort_by' => array(
                            'value' => array(
                                'order' => 'asc', ), ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4059', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Goods\packages-pakety', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Пакеты', 
            'site_title' => array(
                35 => 'Стоимость услуг.. BigBuh - онлайн бухгалтерия нового поколения', ), 
            'site_keywords' => array(
                35 => 'бухгалтерия, онлайн бухгалтерия, отчеты, 910 форма, 200 форма, 300 форма, налоговые отчеты, сдать отчет, квартальный отчет, бизнес, тоо, ип, вести бухгалтерию, аутсорсинг бухгалтерских услуг, бухгалтерские услуги, 1С-бухгалтерия, облачная бухгалтерия, регистрация онлайн бухгалтерия', ), 
            'site_description' => array(
                35 => 'Услуги - облачный сервис ведения бухгалтерского учета через интернет, т.е. электронные услуги (в том числе информационные, интерактивные, транзакционные), предоставляемые на территории Республики Казахстан совершеннолетним дееспособным физическим и юридическим лицам, с применением Информационных технологий', ), ), ), );