<?php
return array(
    3606 => array(
        '/' => array(
            35 => array(
                'site_title' => 'Интернет-магазин продукции HyperX', 
                'site_keywords' => '', 
                'site_description' => '', ), ), 
        '/catalogs' => array(
            35 => array(
                'site_title' => '', 
                'site_keywords' => '', 
                'site_description' => '', ), ), 
        '/basket' => array(
            35 => array(
                'site_title' => '', 
                'site_keywords' => '', 
                'site_description' => '', ), ), 
        '/goods' => array(
            35 => array(
                'site_title' => '', 
                'site_keywords' => '', 
                'site_description' => '', ), ), 
        '/find' => array(
            35 => array(
                'site_title' => '', 
                'site_keywords' => '', 
                'site_description' => '', ), ), 
        '/groups' => array(
            35 => array(
                'site_title' => '', 
                'site_keywords' => '', 
                'site_description' => '', ), ), 
        '/payment-cash' => array(
            35 => array(
                'site_title' => '', 
                'site_keywords' => '', 
                'site_description' => '', ), ), 
        '/payment-card' => array(
            35 => array(
                'site_title' => '', 
                'site_keywords' => '', 
                'site_description' => '', ), ), 
        '/article' => array(
            35 => array(
                'site_title' => '', 
                'site_keywords' => '', 
                'site_description' => '', ), ), ), );