<?php
return array(
    'seo_url' => array(
        '/catalogs' => array(
            'ct_shop_goods' => array(
                'url' => '/goods', 
                'params' => array(
                    'id' => 'id', 
                    'shop_table_rubric_id' => '_current_rubric_', ), ), 
            'ct_shop_table_rubrics' => array(
                'url' => '/catalogs', 
                'params' => array(
                    'id' => 'rubric', ), ), ), 
        '/news' => array(
            'ct_shop_news' => array(
                'url' => '/article', 
                'params' => array(
                    'id' => 'id', ), ), ), 
        '/applying' => array(
            'ct_shop_news' => array(
                'url' => '/applying-article', 
                'params' => array(
                    'id' => 'id', ), ), ), ), 
    'basic' => array(
        1596950468 => array(
            'title' => 'Социальные сети', 
            'table' => 'DB_Shop_New',
            'function' => 'find',
            'one' => 'View_Shop_New\basic\sotcialnye-seti', 
            'params' => array(
                'param_index' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '1', 
                    'value' => '4035', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_News\basic\sotcialnye-seti', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1596950469 => array(
            'title' => 'Телефон сверху', 
            'table' => 'DB_Shop_AddressContact',
            'function' => 'find',
            'one' => 'View_Shop_AddressContact\basic\telefon-sverkhu', 
            'params' => array(
                'limit' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_address_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'contact_type_id' => array(
                    'is_public' => '1', 
                    'value' => '13,14', 
                    'field' => '', ), 
                'city_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'land_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_AddressContacts\basic\telefon-sverkhu', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1596950470 => array(
            'title' => 'E-mail сверху', 
            'table' => 'DB_Shop_AddressContact',
            'function' => 'find',
            'one' => 'View_Shop_AddressContact\basic\e-mail-sverkhu', 
            'params' => array(
                'limit' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_address_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'contact_type_id' => array(
                    'is_public' => '1', 
                    'value' => '98', 
                    'field' => '', ), 
                'city_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'land_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_AddressContacts\basic\e-mail-sverkhu', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1596950471 => array(
            'title' => 'Адрес', 
            'table' => 'DB_Shop_Address',
            'function' => 'getMainShopAddress', 
            'one' => 'View_Shop_Address\basic\adres', 
            'params' => array(), 
            'elements' => array(
                0 => 'land_id', 
                1 => 'city_id', ), 
            'list' => '', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1596950472 => array(
            'title' => 'Телефоны снизу', 
            'table' => 'DB_Shop_AddressContact',
            'function' => 'find',
            'one' => 'View_Shop_AddressContact\basic\telefony-snizu', 
            'params' => array(
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_address_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'contact_type_id' => array(
                    'is_public' => '1', 
                    'value' => '13,14', 
                    'field' => '', ), 
                'city_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'land_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_AddressContacts\basic\telefony-snizu', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1596950473 => array(
            'title' => 'Факс снизу', 
            'table' => 'DB_Shop_AddressContact',
            'function' => 'find',
            'one' => 'View_Shop_AddressContact\basic\faks-snizu', 
            'params' => array(
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_address_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'contact_type_id' => array(
                    'is_public' => '1', 
                    'value' => '100', 
                    'field' => '', ), 
                'city_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'land_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_AddressContacts\basic\faks-snizu', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1596950474 => array(
            'title' => 'E-mail снизу', 
            'table' => 'DB_Shop_AddressContact',
            'function' => 'find',
            'one' => 'View_Shop_AddressContact\basic\e-mail-snizu', 
            'params' => array(
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_address_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'contact_type_id' => array(
                    'is_public' => '1', 
                    'value' => '98', 
                    'field' => '', ), 
                'city_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'land_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_AddressContacts\basic\e-mail-snizu', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), ), 
    'urls' => array(
        '' => array(
            'main' => '/main/index', 
            'data' => array(
                1596955114 => array(
                    'title' => 'Слайдер', 
                    'table' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-slaider', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '10', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4036', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-slaider', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1596955115 => array(
                    'title' => 'Продукция', 
                    'table' => 'DB_Shop_Good',
                    'function' => 'find',
                    'one' => 'View_Shop_Good\-produktciya', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '8', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4037', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Goods\-produktciya', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1596955116 => array(
                    'title' => 'Новости', 
                    'table' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-novosti', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '8', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4038', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-novosti', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Главная', ), 
        '/about' => array(
            'main' => '/main/about', 
            'data' => array(
                1597555474 => array(
                    'title' => 'О компании', 
                    'table' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-about-o-kompanii', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4093', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-about-o-kompanii', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Компания', ), 
        '/catalogs' => array(
            'main' => '/main/catalogs', 
            'data' => array(
                1544094939 => array(
                    'title' => 'Детвора',
                    'table' => 'DB_Shop_Good',
                    'function' => 'find',
                    'one' => 'View_Shop_Good\-products-rubriki-v-snizu',
                    'list' => 'View_Shop_Goods\-products-detvora',
                    'params' => array(
                        'sort_by' => array(
                            'is_public' => '1',
                            'value' => array(
                                'order' => 'asc',
                                'name' => 'asc', ),
                            'field' => '', ),
                        'limit' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'limit_page' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_not_read_request' => array(
                            'is_public' => '1',
                            'value' => '0',
                            'field' => '', ),
                        'type' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'root_id' => array(
                            'is_public' => '1',
                            'value' => '0',
                            'field' => 'rubric', ),
                        'shop_table_select_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'shop_table_unit_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'shop_table_brand_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'created_at_year' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'created_at_month' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_branch' => array(
                            'is_public' => '0',
                            'value' => '0',
                            'field' => '', ),
                        'shop_branch_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'name' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'text' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'options' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_group' => array(
                            'is_public' => '0',
                            'value' => '0',
                            'field' => '', ),
                        'is_public' => array(
                            'is_public' => '0',
                            'value' => '0',
                            'field' => '', ),
                        'shop_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'update_user_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'create_user_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ), ),
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1',
                            'priority' => '1', ),
                        'get' => array(
                            'is_read' => '0',
                            'priority' => '', ),
                        'post' => array(
                            'is_read' => '0',
                            'priority' => '', ), ), ),
                1596958858 => array(
                    'title' => 'Продукция', 
                    'table' => 'DB_Shop_Good',
                    'function' => 'find',
                    'one' => 'View_Shop_Good\-produktciya', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '1', 
                            'value' => '24', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4037', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'rubric', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Goods\-catalogs-produktciya', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1597063510 => array(
                    'title' => 'Рубрика',
                    'table' => 'DB_Shop_Table_Rubric',
                    'function' => 'findOne',
                    'one' => 'View_Shop_Good\-catalogs-rubrika', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'rubric', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1597062416 => array(
                    'title' => 'Хлебные крошки', 
                    'table' => 'DB_Shop_Table_Rubric',
                    'function' => 'findBreadCrumbs',
                    'one' => 'View_Shop_Table_Rubric\-catalogs-khlebnye-kroshki', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '999', 
                            'field' => 'rubric_root_id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Table_Rubrics\-catalogs-khlebnye-kroshki', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Продукты', ), 
        '/applying' => array(
            'main' => '/main/applying', 
            'data' => array(
                1596974165 => array(
                    'title' => 'Применение', 
                    'table' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-applying-primenenie', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '1', 
                            'value' => '24', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4039', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-applying-primenenie', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Применение', ), 
        '/careers' => array(
            'main' => '/main/careers', 
            'data' => array(
                1596974421 => array(
                    'title' => 'Карьера', 
                    'table' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-careers-karera', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4040', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-careers-karera', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => 'й', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Карьера', ), 
        '/contacts' => array(
            'main' => '/main/contacts', 
            'data' => array(
                1596950471 => array(
                    'title' => 'Карта',
                    'table' => 'DB_Shop_Address',
                    'function' => 'getMainShopAddress',
                    'one' => 'View_Shop_Address\-contacts-karta',
                    'params' => array(),
                    'elements' => array(),
                    'list' => '',
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1',
                            'priority' => '1', ),
                        'get' => array(
                            'is_read' => '0',
                            'priority' => '', ),
                        'post' => array(
                            'is_read' => '0',
                            'priority' => '', ), ), ), ),
            'title' => 'Контакты', ), 
        '/news' => array(
            'main' => '/main/news', 
            'data' => array(
                1596958256 => array(
                    'title' => 'Новости', 
                    'table' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-novosti', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '1',
                            'value' => '24',
                            'field' => '', ),
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1',
                            'value' => '4038',
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\index-news-novosti', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Новости', ), 
        '/article' => array(
            'main' => '/main/article', 
            'data' => array(
                1596974737 => array(
                    'title' => 'Статья', 
                    'table' => 'DB_Shop_New',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New\-article-statya', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Статья', ), 
        '/applying-article' => array(
            'main' => '/main/applying-article', 
            'data' => array(
                1596974737 => array(
                    'title' => 'Статья применения', 
                    'table' => 'DB_Shop_New',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New\applying-article-statya', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Статья', ), 
        '/goods' => array(
            'main' => '/main/goods', 
            'data' => array(
                1597049780 => array(
                    'title' => 'Товар', 
                    'table' => 'DB_Shop_Good',
                    'function' => 'findOne',
                    'one' => 'View_Shop_Good\-goods-tovar', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1597062416 => array(
                    'title' => 'Хлебные крошки', 
                    'table' => 'DB_Shop_Table_Rubric',
                    'function' => 'findBreadCrumbs',
                    'one' => 'View_Shop_Table_Rubric\-catalogs-khlebnye-kroshki', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '999', 
                            'field' => 'rubric_root_id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Table_Rubrics\-catalogs-khlebnye-kroshki', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Продукт', ), ), );