<?php
return array(
    'seo_url' => array(
        '/articles' => array(
            'ct_shop_news' => array(
                'url' => '/article',
                'params' => array(
                    'id' => 'id', ), ), ),
        '/data' => array(
            'ct_shop_news' => array(
                'url' => '/data',
                'params' => array(
                    'id' => 'id', ), ), ),
        '/departments' => array(
            'ct_shop_news' => array(
                'url' => '/departments',
                'params' => array(
                    'id' => 'id', ), ), ),
        '/work-stages' => array(
            'ct_shop_news' => array(
                'url' => '/data',
                'params' => array(
                    'id' => 'id', ), ), ), ),
    'basic' => array(
        1547566263 => array(
            'title' => 'Телефон', 
            'db_object' => 'DB_Shop_AddressContact',
            'function' => 'find',
            'one' => 'View_Shop_AddressContact\basic\telefon', 
            'params' => array(
                'limit' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_address_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'contact_type_id' => array(
                    'is_public' => '1', 
                    'value' => '13, 14', 
                    'field' => '', ), 
                'city_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'land_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_AddressContacts\basic\telefon', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), ), 
    'urls' => array(
        '' => array(
            'main' => '/main/index', 
            'data' => array(
                1547566722 => array(
                    'title' => 'Слайдер на главной', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-slaider-na-glavnoi', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '10', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3922', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-slaider-na-glavnoi', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1547566723 => array(
                    'title' => 'О нашей студии', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-o-nashei-studii', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3923', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-o-nashei-studii', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '', ), ), ), 
                1547566724 => array(
                    'title' => 'Как мы работаем', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-kak-my-rabotaem', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3924', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-kak-my-rabotaem', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1547566725 => array(
                    'title' => 'Статьи', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-stati', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '10', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3925', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-stati', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1547568396 => array(
                    'title' => 'Направления', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-napravleniya', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3926', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-napravleniya', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Главная', ), 
        '/portfolio' => array(
            'main' => '/main/portfolio', 
            'data' => array(
                1561277109 => array(
                    'title' => 'Портфолио', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New/-portfolio-portfolio', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '1', 
                            'value' => '16', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3956', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News/-portfolio-portfolio', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Портфолио', ), 
        '/cost-of-work' => array(
            'main' => '/main/cost-of-work', 
            'data' => array(), 
            'title' => 'Стоимость работ', ), 
        '/articles' => array(
            'main' => '/main/articles', 
            'data' => array(
                1561274332 => array(
                    'title' => 'Статьи', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New/-articles-stati', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '1', 
                            'value' => '7', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3925', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News/-articles-stati', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Статьи', ), 
        '/contacts' => array(
            'main' => '/main/contacts', 
            'data' => array(
                1561280954 => array(
                    'title' => 'Карта', 
                    'db_object' => 'DB_Shop_Address',
                    'function' => 'getMainShopAddress', 
                    'one' => 'View_Shop_Address/-contacts-karta', 
                    'params' => array(), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Контакты', ), 
        '/article' => array(
            'main' => '/main/article', 
            'data' => array(
                1561472198 => array(
                    'title' => 'Статья', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New/-article-statya', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Статья', ),
        '/data' => array(
            'main' => '/main/site',
            'data' => array(
                1561826360 => array(
                    'title' => 'Статья',
                    'db_object' => 'DB_Shop_New',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New/-site-statya',
                    'params' => array(
                        'id' => array(
                            'is_public' => '1',
                            'value' => '',
                            'field' => 'id', ),
                        'is_not_read_request' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_branch' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'shop_branch_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_error_404' => array(
                            'is_public' => '1',
                            'value' => '1',
                            'field' => '', ), ),
                    'list' => '',
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1',
                            'priority' => '1', ),
                        'get' => array(
                            'is_read' => '1',
                            'priority' => '3', ),
                        'post' => array(
                            'is_read' => '1',
                            'priority' => '2', ), ), ), ),
            'title' => 'Футтор', ),
        '/departments' => array(
            'main' => '/main/site',
            'data' => array(
                1561826360 => array(
                    'title' => 'Статья',
                    'db_object' => 'DB_Shop_New',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New/-site-statya',
                    'params' => array(
                        'id' => array(
                            'is_public' => '1',
                            'value' => '',
                            'field' => 'id', ),
                        'is_not_read_request' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_branch' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'shop_branch_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_error_404' => array(
                            'is_public' => '1',
                            'value' => '1',
                            'field' => '', ), ),
                    'list' => '',
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1',
                            'priority' => '1', ),
                        'get' => array(
                            'is_read' => '1',
                            'priority' => '3', ),
                        'post' => array(
                            'is_read' => '1',
                            'priority' => '2', ), ), ), ),
            'title' => 'Виды работ', ),
        '/work-stages' => array(
            'main' => '/main/site',
            'data' => array(
                1561826360 => array(
                    'title' => 'Статья',
                    'db_object' => 'DB_Shop_New',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New/-site-statya',
                    'params' => array(
                        'id' => array(
                            'is_public' => '1',
                            'value' => '',
                            'field' => 'id', ),
                        'is_not_read_request' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_branch' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'shop_branch_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_error_404' => array(
                            'is_public' => '1',
                            'value' => '1',
                            'field' => '', ), ),
                    'list' => '',
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1',
                            'priority' => '1', ),
                        'get' => array(
                            'is_read' => '1',
                            'priority' => '3', ),
                        'post' => array(
                            'is_read' => '1',
                            'priority' => '2', ), ), ), ),
            'title' => 'Стадии работ', ), ), );