<?php
return array(
    'seo_url' => array(
        '/trucks' => array(
            'ct_shop_table_rubrics' => array(
                'url' => '/trucks', 
                'params' => array(
                    'id' => 'rubric', ), ), 
            'ct_shop_cars' => array(
                'url' => '/truck', 
                'params' => array(
                    'id' => 'id', ), ), ), 
        '/articles' => array(
            'ct_shop_table_rubrics' => array(
                'url' => '/articles', 
                'params' => array(
                    'id' => 'rubric', ), ), 
            'ct_shop_news' => array(
                'url' => '/article', 
                'params' => array(
                    'id' => 'id', ), ), ), ), 
    'basic' => array(
        1550034425 => array(
            'title' => 'Количество машин', 
            'db_object' => 'DB_Shop_Car',
            'function' => 'getCountShopCars', 
            'one' => 'View_Shop_Car\-kolichestvo-mashin', 
            'params' => array(
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '1', 
                    'value' => '3968', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_Cars\-kolichestvo-mashin', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1550034943 => array(
            'title' => 'Языки',
            'class' => 'View_Shop',
            'db_object' => 'DB_Language',
            'function' => 'getShopLanguages', 
            'one' => 'View_Language\basic\yazyki', 
            'params' => array(), 
            'list' => 'View_Languages\basic\yazyki', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1552030216 => array(
            'title' => 'Курсы валют', 
            'db_object' => 'DB_Currency',
            'function' => 'findCurrencies', 
            'one' => 'View_Currency\basic\kursy-valyut', 
            'params' => array(
                'id' => array(
                    'is_public' => '1', 
                    'value' => array(
                        0 => 19, 
                        1 => 22, ), 
                    'field' => '', ), ), 
            'list' => 'View_Currencys\basic\kursy-valyut', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1552394908 => array(
            'title' => 'Телефоны в самом верху', 
            'db_object' => 'DB_Shop_AddressContact',
            'function' => 'find',
            'one' => 'View_Shop_AddressContact\basic\telefony-v-samom-verkhu', 
            'params' => array(
                'limit' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_address_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'contact_type_id' => array(
                    'is_public' => '1', 
                    'value' => '13, 14', 
                    'field' => '', ), 
                'city_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'land_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_AddressContacts\basic\telefony-v-samom-verkhu', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1552878926 => array(
            'title' => 'Социальные сети', 
            'db_object' => 'DB_Shop_New',
            'function' => 'find',
            'one' => 'View_Shop_New\basic\sotcialnye-seti', 
            'params' => array(
                'param_index' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '0',
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '1', 
                    'value' => '4741', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_News\basic\sotcialnye-seti', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), ), 
    'urls' => array(
        '' => array(
            'main' => '/main/index', 
            'data' => array(
                1550035465 => array(
                    'title' => 'Рубрикация продажи', 
                    'db_object' => 'DB_Shop_Car',
                    'function' => 'find',
                    'one' => 'View_Shop_Car\-rubrikatciya', 
                    'params' => array(
                        'sort_by' => array(
                            'is_public' => '1', 
                            'value' => array(
                                'order' => 'asc', 
                                'name' => 'acs', ), 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '6', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3968', 
                            'field' => '', ), 
                        'root_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Cars\-rubrikatciya', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1550035466 => array(
                    'title' => 'Новые машины', 
                    'db_object' => 'DB_Shop_Car',
                    'function' => 'find', 
                    'one' => 'View_Shop_Car\-novye-mashiny', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '10', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3968', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Cars\-novye-mashiny', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1550035909 => array(
                    'title' => 'Количество машин на главной', 
                    'db_object' => 'DB_Shop_Car',
                    'function' => 'getCountShopCars', 
                    'one' => 'View_Shop_Car\-kolichestvo-mashin-na-glavnoy', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3968', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Cars\-kolichestvo-mashin-na-glavnoy', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '', ), ), ), 
                1551265141 => array(
                    'title' => 'Марки', 
                    'db_object' => 'DB_Shop_Mark',
                    'function' => 'findAll',
                    'one' => 'View_Shop_Mark\-marki', 
                    'params' => array(
                        'sort_by' => array(
                            'is_public' => '1', 
                            'value' => array(
                                'order' => 'asc', 
                                'name' => 'acs', ), 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3966', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Marks\-marki', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1551268841 => array(
                    'title' => 'Страны', 
                    'db_object' => 'DB_Land',
                    'function' => 'findAll',
                    'one' => 'View_Land\-strany', 
                    'params' => array(
                        'sort_by' => array(
                            'is_public' => '1', 
                            'value' => array(
                                'order' => 'asc', 
                                'name' => 'acs', ), 
                            'field' => '', ), ), 
                    'list' => 'View_Lands\-strany', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Главная', ), 
        '/truck' => array(
            'main' => '/main/truck', 
            'data' => array(
                1550676347 => array(
                    'title' => 'Машина', 
                    'db_object' => 'DB_Shop_Car',
                    'function' => 'findOne',
                    'one' => 'View_Shop_Car\-truck-mashina', 
                    'elements' => array(
                        0 => 'shop_table_rubric_id', 
                        1 => 'shop_model_id', 
                        2 => 'shop_mark_id', 
                        3 => 'location_land_id', 
                        4 => 'production_land_id', 
                        5 => 'shop_table_param_4_id', 
                        6 => 'currency_id', ), 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1550676373 => array(
                    'title' => 'Хлебные крошки', 
                    'db_object' => 'DB_Shop_Table_Rubric',
                    'function' => 'findBreadCrumbs',
                    'one' => 'View_Shop_Table_Rubric\-truck-khlebnye-kroshki', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '_root_id_', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Table_Rubrics\-truck-khlebnye-kroshki', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1551937563 => array(
                    'title' => 'Контакты менеджера', 
                    'db_object' => 'DB_Shop_Table_Param',
                    'function' => 'findShopTableParams', 
                    'one' => 'View_Shop_Table_Param\-truck-kontakty-menedzhera', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '1', 
                            'value' => '4', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4494', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Table_Params\-truck-kontakty-menedzhera', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Машина', ), 
        '/trucks' => array(
            'main' => '/main/trucks', 
            'data' => array(
                1550036371 => array(
                    'title' => 'Машины', 
                    'db_object' => 'DB_Shop_Car',
                    'function' => 'find', 
                    'one' => 'View_Shop_Car\-trucks-mashiny', 
                    'elements' => array(
                        'shop_table_param_1_id' => array(
                            0 => 'name', ), 
                        'shop_table_rubric_id' => array(
                            0 => 'name', 
                            1 => 'name_url', ), 
                        'location_land_id' => array(
                            0 => 'name', ), 
                        'currency_id' => array(
                            0 => 'name', 
                            1 => 'currency_rate', 
                            2 => 'is_round', 
                            3 => 'symbol', ), ), 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '1', 
                            'value' => '15', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3968', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'rubric', ), 
                        'shop_mark_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'mark', ), 
                        'shop_model_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'model', ), 
                        'param_1_int' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'year', ), 
                        'location_land_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'land', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Cars\-trucks-mashiny', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1550036372 => array(
                    'title' => 'Рубрика',
                    'db_object' => 'DB_Shop_Table_Rubric',
                    'function' => 'findOne',
                    'one' => 'View_Shop_Car\-trucks-rubrika', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => 'rubric', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1550036373 => array(
                    'title' => 'Рубрики', 
                    'db_object' => 'DB_Shop_Car',
                    'function' => 'find',
                    'one' => 'View_Shop_Car\-trucks-rubriki', 
                    'params' => array(
                        'sort_by' => array(
                            'is_public' => '1', 
                            'value' => array(
                                'order' => 'asc', 
                                'name' => 'acs', ), 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '20', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3968', 
                            'field' => '', ), 
                        'root_id' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => 'rubric', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Cars\-trucks-rubriki', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1550036374 => array(
                    'title' => 'Хлебные крошки', 
                    'db_object' => 'DB_Shop_Table_Rubric',
                    'function' => 'findBreadCrumbs',
                    'one' => 'View_Shop_Table_Rubric\-trucks-khlebnye-kroshki', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '999', 
                            'field' => '_root_id_', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Table_Rubrics\-trucks-khlebnye-kroshki', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1551272988 => array(
                    'title' => 'Марки', 
                    'db_object' => 'DB_Shop_Mark',
                    'function' => 'findShopMarksByCars', 
                    'one' => 'View_Shop_Mark\-trucks-marki', 
                    'params' => array(
                        'params_car' => array(
                            'limit' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'limit_page' => array(
                                'is_public' => '0', 
                                'value' => '0', 
                                'field' => '', ), 
                            'is_not_read_request' => array(
                                'is_public' => '0', 
                                'value' => '0', 
                                'field' => '', ), 
                            'type' => array(
                                'is_public' => '1', 
                                'value' => '3968', 
                                'field' => '', ), 
                            'shop_table_rubric_id' => array(
                                'is_public' => '1', 
                                'value' => '', 
                                'field' => 'rubric', ), 
                            'shop_mark_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'shop_model_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'location_land_id' => array(
                                'is_public' => '1', 
                                'value' => '', 
                                'field' => 'land', ), 
                            'created_at_year' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'created_at_month' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'is_branch' => array(
                                'is_public' => '0', 
                                'value' => '0', 
                                'field' => '', ), 
                            'shop_branch_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'name' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'text' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'options' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'is_public' => array(
                                'is_public' => '0', 
                                'value' => '0', 
                                'field' => '', ), 
                            'shop_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'update_user_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), 
                            'create_user_id' => array(
                                'is_public' => '0', 
                                'value' => '', 
                                'field' => '', ), ), 
                        'sort_by' => array(
                            'is_public' => '1', 
                            'value' => array(
                                'order' => 'asc', 
                                'name' => 'acs', ), 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3966', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Marks\-trucks-marki', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1551272989 => array(
                    'title' => 'Страны нахождения', 
                    'db_object' => 'DB_Land',
                    'function' => 'findAll',
                    'one' => 'View_Land\-trucks-strany-nakhozhdeniya', 
                    'params' => array(
                        'sort_by' => array(
                            'is_public' => '1', 
                            'value' => array(
                                'name' => 'acs', ), 
                            'field' => '', ), ), 
                    'list' => 'View_Lands\-trucks-strany-nakhozhdeniya', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Список машин', ), 
        '/articles' => array(
            'main' => '/main/articles', 
            'data' => array(
                1551516383 => array(
                    'title' => 'Статьи', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-articles-stati', 
                    'is_load_one' => '1', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '1', 
                            'value' => '12', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4042', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'rubric', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-articles-stati', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Новости', ), 
        '/article' => array(
            'main' => '/main/article', 
            'data' => array(
                1551520189 => array(
                    'title' => 'Статья', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New\-article-statya', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1551520359 => array(
                    'title' => 'Хлебные крошки', 
                    'db_object' => 'DB_Shop_Table_Rubric',
                    'function' => 'findBreadCrumbs',
                    'one' => 'View_Shop_Table_Rubric\-article-khlebnye-kroshki', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '999', 
                            'field' => '_root_id_', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Table_Rubrics\-article-khlebnye-kroshki', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Новость', ), 
        '/get-models' => array(
            'main' => '/main/get-models', 
            'data' => array(
                1551267102 => array(
                    'title' => 'Модели', 
                    'db_object' => 'DB_Shop_Model',
                    'function' => 'find',
                    'one' => 'View_Shop_Model\-get-models-modeli', 
                    'params' => array(
                        'sort_by' => array(
                            'is_public' => '1', 
                            'value' => array(
                                'order' => 'asc', 
                                'name' => 'acs', ), 
                            'field' => '', ), 
                        'shop_mark_id' => array(
                            'is_public' => '1', 
                            'value' => '0', 
                            'field' => 'shop_mark_id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Models\-get-models-modeli', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Модели', ), 
        '/spares' => array(
            'main' => '/main/spares', 
            'data' => array(
                1551515888 => array(
                    'title' => 'Статья запчастей', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-spares-statya-zapchastei', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => 'ё', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4040', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-spares-statya-zapchastei', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Запчасти', ), 
        '/truck-add' => array(
            'main' => '/main/truck-add', 
            'data' => array(), 
            'title' => 'Добавить объявление', ), 
        '/about' => array(
            'main' => '/main/about', 
            'data' => array(
                1551933263 => array(
                    'title' => 'О компании', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-about-o-kompanii', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4471', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-about-o-kompanii', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'О компании', ), 
        '/trucks-find' => array(
            'main' => '/main/trucks-find', 
            'data' => array(
                1550036371 => array(
                    'title' => 'Машины', 
                    'db_object' => 'DB_Shop_Car',
                    'function' => 'find', 
                    'one' => 'View_Shop_Car\-trucks-mashiny', 
                    'elements' => array(
                        'shop_table_param_1_id' => array(
                            0 => 'name', ), 
                        'shop_table_rubric_id' => array(
                            0 => 'name', 
                            1 => 'name_url', ), 
                        'location_land_id' => array(
                            0 => 'name', ), ), 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '1', 
                            'value' => '15', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3968', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'rubric', ), 
                        'shop_mark_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'mark', ), 
                        'shop_model_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'model', ), 
                        'param_1_int' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'year', ), 
                        'location_land_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'land', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_Cars\-trucks-mashiny', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Поиск по фильтрам', ), ), );