<?php
return array(
    'seo_url' => array(
        '/catalogs' => array(
            'ct_shop_goods' => array(
                'url' => '/goods', 
                'params' => array(
                    'id' => 'id', 
                    'shop_table_rubric_id' => 'rubric', ), ), 
            'ct_shop_table_rubrics' => array(
                'url' => '/catalogs', 
                'params' => array(
                    'id' => 'rubric', ), ), ), 
        '/services' => array(
            'ct_shop_news' => array(
                'url' => '/service', 
                'params' => array(
                    'id' => 'id', ), ), ), 
        '/articles' => array(
            'ct_shop_news' => array(
                'url' => '/article', 
                'params' => array(
                    'id' => 'id', ), ), ), ), 
    'basic' => array(
        1574999537 => array(
            'title' => 'Количество товаров в корзине', 
            'table' => 'DB_Shop_Cart', 
            'function' => 'getCartShopGoods', 
            'one' => 'View_Shop_Cart\basic\kolichestvo-tovarov-v-korzine', 
            'params' => array(
                'param_index' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_Carts\basic\kolichestvo-tovarov-v-korzine', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '', ), 
                'get' => array(
                    'is_read' => '1', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '1', 
                    'priority' => '', ), ), ), 
        15749995371 => array(
            'title' => 'Количество товаров в избранном', 
            'table' => 'DB_Shop_Good', 
            'class' => 'View_Favorite', 
            'function' => 'getCountShopGoods', 
            'one' => 'DB_Shop_Good\basic\kolichestvo-tovarov-v-igbrannom', 
            'params' => array(), 
            'list' => '', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '', ), 
                'get' => array(
                    'is_read' => '1', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '1', 
                    'priority' => '', ), ), ), 
        1623046090 => array(
            'title' => 'Телефон сверху', 
            'class' => 'View_Shop_Table_View', 
            'table' => 'DB_Shop_AddressContact', 
            'function' => 'find', 
            'one' => 'DB_Shop_AddressContact\basic\telefon-sverkhu', 
            'params' => array(
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '1', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '0', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_address_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'contact_type_id' => array(
                    'is_public' => '0', 
                    'value' => '13,14', 
                    'field' => '', ), 
                'city_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'land_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '0', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'DB_Shop_AddressContacts\basic\telefon-sverkhu', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '1', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '1', 
                    'priority' => '', ), ), ), 
        1623046610 => array(
            'title' => 'Дерево рубрик', 
            'class' => 'View_Shop_Table_View', 
            'table' => 'DB_Shop_Good', 
            'function' => 'findRubrics', 
            'one' => 'DB_Shop_Good\basic\derevo-rubrik', 
            'params' => array(
                'sort_by' => array(
                    'is_public' => '1', 
                    'value' => array(
                        'order' => 'asc', 
                        'name' => 'asc', ), 
                    'field' => '', ), 
                'param_index' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '1', ), 
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '1', 
                    'value' => '4042', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_tree' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '#is_tree#', ), ), 
            'list' => 'DB_Shop_Goods\basic\derevo-rubrik', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1623047092 => array(
            'title' => 'Услуги меню', 
            'class' => 'View_Shop_Table_View', 
            'table' => 'DB_Shop_New', 
            'function' => 'find', 
            'one' => 'DB_Shop_New\basic\uslugi-menyu', 
            'params' => array(
                'sort_by' => array(
                    'is_public' => '1', 
                    'value' => array(
                        'order' => 'asc', 
                        'name' => 'asc', ), 
                    'field' => '', ), 
                'param_index' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '1', 
                    'value' => '4043', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'DB_Shop_News\basic\uslugi-menyu', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1623047161 => array(
            'title' => 'Системные страницы', 
            'class' => 'View_Shop_Table_View', 
            'table' => 'DB_Shop_New', 
            'function' => 'find', 
            'one' => 'DB_Shop_New\basic\sistemnye-stranitcy', 
            'params' => array(
                'sort_by' => array(
                    'is_public' => '1', 
                    'value' => array(
                        'order' => 'asc', 
                        'name' => 'asc', ), 
                    'field' => '', ), 
                'param_index' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '1', 
                    'value' => '4044', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'DB_Shop_News\basic\sistemnye-stranitcy', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '1', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), ), 
    'urls' => array(
        '' => array(
            'main' => '/main/index', 
            'data' => array(
                1623059697 => array(
                    'title' => 'На главную', 
                    'class' => 'View_Shop_Table_View', 
                    'table' => 'DB_Shop_New', 
                    'function' => 'find', 
                    'one' => 'DB_Shop_New\-na-glavnuyu', 
                    'params' => array(
                        'sort_by' => array(
                            'is_public' => '1', 
                            'value' => array(
                                'order' => 'asc', 
                                'name' => 'asc', ), 
                            'field' => '', ), 
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4045', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'DB_Shop_News\-na-glavnuyu', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Главная', ), 
        '/catalogs' => array(
            'main' => '/main/catalogs', 
            'data' => array(
                1623061000 => array(
                    'title' => 'Рубрика', 
                    'class' => 'View_Shop_Table_Rubric', 
                    'table' => 'DB_Shop_Table_Rubric', 
                    'function' => 'findOne', 
                    'one' => 'DB_Shop_Table_Rubric\-catalog-rubrika', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '999', 
                            'field' => 'rubric', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ),
                1597062416 => array(
                    'title' => 'Детвора',
                    'table' => 'DB_Shop_Table_Rubric',
                    'function' => 'find',
                    'list' => 'DB_Shop_Table_Rubrics\child',
                    'one' => 'DB_Shop_Table_Rubric\child',
                    'params' => array(
                        'id' => array(
                            'is_public' => '0',
                            'value' => '0',
                            'field' => '0', ),
                        'root_id' => array(
                            'is_public' => '1',
                            'value' => '0',
                            'field' => 'rubric', ),
                        'is_not_read_request' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_branch' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'shop_branch_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_error_404' => array(
                            'is_public' => '1',
                            'value' => '0',
                            'field' => '', ), ),
                ),
                1623061905 => array(
                    'title' => 'Товары', 
                    'class' => 'View_Shop_Table_View', 
                    'table' => 'DB_Shop_Good', 
                    'function' => 'find', 
                    'one' => 'DB_Shop_Good\-catalog-tovary', 
                    'params' => array(
                        'is_public_ignore' => array(
                            'is_public' => '1',
                            'value' => '1',
                            'field' => '', ),
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'main_shop_table_rubric_id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'rubric', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'DB_Shop_Goods\-catalog-tovary', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Каталог', ), 
        '/goods' => array(
            'main' => '/main/goods', 
            'data' => array(
                1623062483 => array(
                    'title' => 'Товар', 
                    'class' => 'View_Shop_Table_View', 
                    'table' => 'DB_Shop_Good', 
                    'function' => 'findOne', 
                    'one' => 'DB_Shop_Good\-good-tovar', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '999', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), 
                1623126637 => array(
                    'title' => 'Хэштеги товара', 
                    'class' => 'View_Shop_Table_View', 
                    'table' => 'DB_Shop_Good', 
                    'function' => 'getHashtagsByDBObject', 
                    'one' => 'DB_Shop_Good\-goods-kheshtegi-tovara', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => 'DB_Shop_Goods\-goods-kheshtegi-tovara', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Товар', ), 
        '/cart' => array(
            'main' => '/main/cart', 
            'data' => array(
                1623081304 => array(
                    'title' => 'Товары в корзине', 
                    'class' => 'View_Shop_Cart', 
                    'table' => 'DB_Shop_Good', 
                    'function' => 'getCartShopGoods', 
                    'one' => 'DB_Shop_Good\-cart-tovary-v-korzine', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'DB_Shop_Goods\-cart-tovary-v-korzine', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Корзина', ), 
        '/contacts' => array(
            'main' => '/main/contacts', 
            'data' => array(
                1623047161 => array(
                    'title' => 'Текстовка контакты',
                    'class' => 'View_Shop_Table_View',
                    'table' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'DB_Shop_New\contact',
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'limit' => array(
                            'is_public' => '1',
                            'value' => '1',
                            'field' => '', ),
                        'limit_page' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_not_read_request' => array(
                            'is_public' => '1',
                            'value' => '1',
                            'field' => '', ),
                        'type' => array(
                            'is_public' => '1',
                            'value' => '4595',
                            'field' => '', ),
                        'shop_table_rubric_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'shop_table_select_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'shop_table_brand_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'shop_table_unit_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'created_at_year' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'created_at_month' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_branch' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'shop_branch_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'name' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'article' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'text' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'options' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_group' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'is_public' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'shop_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'update_user_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ),
                        'create_user_id' => array(
                            'is_public' => '0',
                            'value' => '',
                            'field' => '', ), ),
                    'list' => 'DB_Shop_News\contact',
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1',
                            'priority' => '1', ),
                        'get' => array(
                            'is_read' => '1',
                            'priority' => '', ),
                        'post' => array(
                            'is_read' => '0',
                            'priority' => '', ), ), ),
                1623063125 => array(
                    'title' => 'Телефоны', 
                    'class' => 'View_Shop_Table_View', 
                    'table' => 'DB_Shop_AddressContact', 
                    'function' => 'find', 
                    'one' => 'DB_Shop_AddressContact\-contacts-telefony', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_address_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'contact_type_id' => array(
                            'is_public' => '1', 
                            'value' => '13,14', 
                            'field' => '', ), 
                        'city_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'land_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'DB_Shop_AddressContacts\-contacts-telefony', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1623063347 => array(
                    'title' => 'Адрес', 
                    'class' => 'View_Shop_Address', 
                    'table' => 'DB_Shop_Address', 
                    'function' => 'getMainShopAddress', 
                    'one' => 'DB_Shop_Address\-contacts-adres', 
                    'params' => array(), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Контакты', ), 
        '/service' => array(
            'main' => '/main/service', 
            'data' => array(
                1623063736 => array(
                    'title' => 'Услуга', 
                    'class' => 'View_Shop_Table_View', 
                    'table' => 'DB_Shop_New', 
                    'function' => 'findOne', 
                    'one' => 'DB_Shop_New\-service-usluga', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Услуга', ), 
        '/favorite' => array(
            'main' => '/main/favorite', 
            'data' => array(
                1623303649 => array(
                    'title' => 'Товары в избранном', 
                    'class' => 'View_Favorite', 
                    'table' => 'DB_Shop_Good', 
                    'function' => 'getShopGoods', 
                    'one' => 'DB_Shop_Good\-catalog-tovary', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'DB_Shop_Goods\-favorite-tovary-v-izbrannom', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Избранные', ), 
        '/article' => array(
            'main' => '/main/article', 
            'data' => array(
                1623063736 => array(
                    'title' => 'Услуга', 
                    'class' => 'View_Shop_Table_View', 
                    'table' => 'DB_Shop_New', 
                    'function' => 'findOne', 
                    'one' => 'DB_Shop_New\-service-usluga', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Статья', ),
        '/cart-success' => array(
            'main' => '/main/cart-success',
            'data' => array( ),
            'title' => 'Успешное оформление заказа', ),
        '/cart-fail' => array(
            'main' => '/main/cart-fail',
            'data' => array( ),
            'title' => 'Не успешное оформление заказа', ),  ), );