<?php
return array(
    'seo_url' => array(
        '/pages' => array(
            'ct_shop_news' => array(
                'url' => '/transportation', 
                'params' => array(
                    'id' => 'id', ), ), ), 
        '/service' => array(
            'ct_shop_news' => array(
                'url' => '/transportation', 
                'params' => array(
                    'id' => 'id', ), ), ), 
        '/delivery' => array(
            'ct_shop_news' => array(
                'url' => '/transportation', 
                'params' => array(
                    'id' => 'id', ), ), ), 
        '/transportation' => array(
            'ct_shop_news' => array(
                'url' => '/transportation', 
                'params' => array(
                    'id' => 'id', ), ), ), ), 
    'basic' => array(
        1561054271 => array(
            'title' => 'Виды перевозок', 
            'db_object' => 'DB_Shop_New',
            'function' => 'find',
            'one' => 'View_Shop_New/basic/vidy-perevozok', 
            'params' => array(
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '1', 
                    'value' => '4078', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_News/basic/vidy-perevozok', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1561055026 => array(
            'title' => 'Отзывы', 
            'db_object' => 'DB_Shop_New',
            'function' => 'find',
            'one' => 'View_Shop_New/basic/otzyvy', 
            'params' => array(
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '1', 
                    'value' => '4099', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_News/basic/otzyvy', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), 
        1564046603 => array(
            'title' => 'Социальные сети', 
            'db_object' => 'DB_Shop_New',
            'function' => 'find',
            'one' => 'View_Shop_New\basic\sotcialnye-seti', 
            'params' => array(
                'param_index' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'limit_page' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_not_read_request' => array(
                    'is_public' => '1', 
                    'value' => '1', 
                    'field' => '', ), 
                'type' => array(
                    'is_public' => '1', 
                    'value' => '4075', 
                    'field' => '', ), 
                'shop_table_rubric_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_select_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_brand_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_table_unit_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_year' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'created_at_month' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_branch' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_branch_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'name' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'article' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'text' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'options' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_group' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'is_public' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'shop_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'update_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), 
                'create_user_id' => array(
                    'is_public' => '0', 
                    'value' => '', 
                    'field' => '', ), ), 
            'list' => 'View_Shop_News\basic\sotcialnye-seti', 
            'read_request_type' => array(
                'params' => array(
                    'is_read' => '1', 
                    'priority' => '1', ), 
                'get' => array(
                    'is_read' => '0', 
                    'priority' => '', ), 
                'post' => array(
                    'is_read' => '0', 
                    'priority' => '', ), ), ), ), 
    'urls' => array(
        '' => array(
            'main' => '/main/index', 
            'data' => array(
                1561051781 => array(
                    'title' => 'Услуги', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New/-uslugi', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4114', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '0', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News/-uslugi', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1561051782 => array(
                    'title' => 'Доставка по городам', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New/-dostavka-po-gorodam', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4130', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News/-dostavka-po-gorodam', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), 
                1561052749 => array(
                    'title' => 'Текст на главную', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New/-tekst-na-glavnuyu', 
                    'params' => array(
                        'limit' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '4112', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News/-tekst-na-glavnuyu', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '0', 
                            'priority' => '', ), 
                        'post' => array(
                            'is_read' => '0', 
                            'priority' => '', ), ), ), ), 
            'title' => 'Главная', ), 
        '/pages.html' => array(
            'main' => '/main/pages.html', 
            'data' => array(
                1560191315 => array(
                    'title' => 'Статьи', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'find',
                    'one' => 'View_Shop_New\-pages.html-stati', 
                    'params' => array(
                        'param_index' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'limit_page' => array(
                            'is_public' => '1', 
                            'value' => '10', 
                            'field' => '', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'type' => array(
                            'is_public' => '1', 
                            'value' => '3986', 
                            'field' => '', ), 
                        'shop_table_rubric_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_select_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_brand_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_table_unit_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_year' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'created_at_month' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'name' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'article' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'text' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'options' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_group' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_public' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'update_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'create_user_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), ), 
                    'list' => 'View_Shop_News\-pages.html-stati', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Статьи', ), 
        '/pages' => array(
            'main' => '/main/pages', 
            'data' => array(
                1560192608 => array(
                    'title' => 'Статья', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New\-pages-statya', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Статья', ), 
        '/incoterms.html' => array(
            'main' => '/main/incoterms.html', 
            'data' => array(), 
            'title' => 'Инкотермс', ), 
        '/contact.html' => array(
            'main' => '/main/contact.html', 
            'data' => array(), 
            'title' => 'Контакты', ), 
        '/service' => array(
            'main' => '/main/service', 
            'data' => array(
                1561055866 => array(
                    'title' => 'Статья', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New/-transportation-statya', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Услуга', ), 
        '/delivery' => array(
            'main' => '/main/delivery', 
            'data' => array(
                1561055866 => array(
                    'title' => 'Статья', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New/-transportation-statya', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Доставка в города', ), 
        '/transportation' => array(
            'main' => '/main/transportation', 
            'data' => array(
                1561055866 => array(
                    'title' => 'Статья', 
                    'db_object' => 'DB_Shop_New',
                    'function' => 'findOne',
                    'one' => 'View_Shop_New/-transportation-statya', 
                    'params' => array(
                        'id' => array(
                            'is_public' => '1', 
                            'value' => '', 
                            'field' => 'id', ), 
                        'is_not_read_request' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_branch' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'shop_branch_id' => array(
                            'is_public' => '0', 
                            'value' => '', 
                            'field' => '', ), 
                        'is_error_404' => array(
                            'is_public' => '1', 
                            'value' => '1', 
                            'field' => '', ), ), 
                    'list' => '', 
                    'read_request_type' => array(
                        'params' => array(
                            'is_read' => '1', 
                            'priority' => '1', ), 
                        'get' => array(
                            'is_read' => '1', 
                            'priority' => '3', ), 
                        'post' => array(
                            'is_read' => '1', 
                            'priority' => '2', ), ), ), ), 
            'title' => 'Виды доставок', ), ), );